Update push-to-newyork.yaml

diff --git a/.github/workflows/push-to-newyork.yaml b/.github/workflows/push-to-newyork.yaml
--- a/.github/workflows/push-to-newyork.yaml
+++ b/.github/workflows/push-to-newyork.yaml
@@ -24,17 +24,17 @@ jobs:
 
     - name: List files in SSL directory
       run: |
-        ls -l newyork-01/etc/nginx/ssl
-        cat newyork-01/etc/nginx/ssl/server.crt.pem || echo "server.crt.pem not found"
-        cat newyork-01/etc/nginx/ssl/server.key || echo "server.key not found"
+        ls -l  Dallas/etc/nginx/ssl
+        cat Dallas/etc/nginx/ssl/server.crt.pem || echo "server.crt.pem not found"
+        cat Dallas/etc/nginx/ssl/server.key || echo "server.key not found"
 
     - name: Set environment variables for base64 encoded config files
       run: |
-        echo "NGINX_CONF_CONFIG_FILE=$(echo '# Modified by NGINX One API $(date) branch: ${{ env.N1SC_BRANCH }} commit hash: ${{ env.N1SC_COMMIT_HASH }}' | cat - newyork-01/etc/nginx/nginx.conf | base64 -w 0)" >> $GITHUB_ENV
-        echo "MIME_TYPES_CONFIG_FILE=$(cat newyork-01/etc/nginx/mime.types | base64 -w 0)" >> $GITHUB_ENV
-        echo "DEFAULT_CONF_CONFIG_FILE=$(cat newyork-01/etc/nginx/conf.d/default.conf | base64 -w 0)" >> $GITHUB_ENV
-        echo "SSL_CERT=$(cat newyork-01/etc/nginx/ssl/server.crt.pem | base64 -w 0)" >> $GITHUB_ENV
-        echo "SSL_KEY=$(cat newyork-01/etc/nginx/ssl/server.key | base64 -w 0)" >> $GITHUB_ENV
+        echo "NGINX_CONF_CONFIG_FILE=$(echo '# Modified by NGINX One API $(date) branch: ${{ env.N1SC_BRANCH }} commit hash: ${{ env.N1SC_COMMIT_HASH }}' | cat - Dallas/etc/nginx/nginx.conf | base64 -w 0)" >> $GITHUB_ENV
+        echo "MIME_TYPES_CONFIG_FILE=$(cat Dallas/etc/nginx/mime.types | base64 -w 0)" >> $GITHUB_ENV
+        echo "DEFAULT_CONF_CONFIG_FILE=$(cat Dallas/etc/nginx/conf.d/default.conf | base64 -w 0)" >> $GITHUB_ENV
+        echo "SSL_CERT=$(cat Dallas/etc/nginx/ssl/server.crt.pem | base64 -w 0)" >> $GITHUB_ENV
+        echo "SSL_KEY=$(cat Dallas/etc/nginx/ssl/server.key | base64 -w 0)" >> $GITHUB_ENV
 
     - name: API call to NGINX One SaaS Console - Fetch Instances
       run: |
@@ -46,7 +46,7 @@ jobs:
       run: |
         RESPONSE=$(curl -X PUT --location 'https://nginx-tenant1.staging.volterra.us/api/nginx/one/namespaces/default/instances/${{ vars.N1SC_INSTANCE }}/config' \
           -H 'Authorization: APIToken ${{ secrets.XC_API_TOKEN }}' \
-          --data '{ "aux": [], "conf_path": "/etc/nginx/nginx.conf", "configs": [ { "files": [ { "contents": "${{ env.NGINX_CONF_CONFIG_FILE }}", "mtime": "1970-01-01T00:00:00Z", "name": "nginx.conf", "size": 2756 }, { "contents": "${{ env.MIME_TYPES_CONFIG_FILE }}", "mtime": "1970-01-01T00:00:00Z", "name": "mime.types", "size": 2756} ], "name": "/etc/nginx" }, { "files": [ { "contents": "${{ env.DEFAULT_CONF_CONFIG_FILE }}", "mtime": "1970-01-01T00:00:00Z", "name": "default.conf", "size": 908 } ], "name": "/etc/nginx/conf.d" }, { "files": [ { "contents": "${{ env.SSL_CERT }}", "mtime": "1970-01-01T00:00:00Z", "name": "server.crt", "size": 2048 }, { "contents": "${{ env.SSL_KEY }}", "mtime": "1970-01-01T00:00:00Z", "name": "server.key", "size": 2048 } ], "name": "/etc/nginx/ssl" }], "object_id": "inst_OaV4v1QXRGm_T1atbMbLJw" }' \
+          --data '{ "aux": [], "conf_path": "/etc/nginx/nginx.conf", "configs": [ { "files": [ { "contents": "${{ env.NGINX_CONF_CONFIG_FILE }}", "mtime": "1970-01-01T00:00:00Z", "name": "nginx.conf", "size": 2756 }, { "contents": "${{ env.MIME_TYPES_CONFIG_FILE }}", "mtime": "1970-01-01T00:00:00Z", "name": "mime.types", "size": 2756} ], "name": "/etc/nginx" }, { "files": [ { "contents": "${{ env.DEFAULT_CONF_CONFIG_FILE }}", "mtime": "1970-01-01T00:00:00Z", "name": "default.conf", "size": 908 } ], "name": "/etc/nginx/conf.d" }, { "files": [ { "contents": "${{ env.SSL_CERT }}", "mtime": "1970-01-01T00:00:00Z", "name": "server.crt", "size": 2048 }, { "contents": "${{ env.SSL_KEY }}", "mtime": "1970-01-01T00:00:00Z", "name": "server.key", "size": 2048 } ], "name": "/etc/nginx/ssl" }], "object_id": "inst_Tg7G7xbRQxKh02kBVtt3AQ" }' \
           -H "Content-Type: application/json")
         echo "Response: $RESPONSE"
         echo "$RESPONSE" | jq . || echo "Failed to parse JSON response"
