Update push-to-newyork.yaml

diff --git a/.github/workflows/push-to-newyork.yaml b/.github/workflows/push-to-newyork.yaml
--- a/.github/workflows/push-to-newyork.yaml
+++ b/.github/workflows/push-to-newyork.yaml
@@ -16,7 +16,7 @@ jobs:
 
       - name: Set misc environment variables
         run: |
-          echo "XC_BEARER_TOKEN=${{ secrets.XC_BEARER_TOKEN }}" >> $GITHUB_ENV
+          echo "XC_API_TOKEN=${{ secrets.XC_API_TOKEN }}" >> $GITHUB_ENV
           echo "N1SC_TIMESTAMP=$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")" >> $GITHUB_ENV
           echo "N1SC_COMMIT_HASH=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
           echo "N1SC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
@@ -30,15 +30,16 @@ jobs:
       - name: API call to NGINX One Saas Console - Fetch Instances
         run: |
           curl --location 'https://${{ vars.N1SC_HOSTNAME }}${{ vars.N1SC_API_PATH }}/${{ vars.N1SC_NAMESPACE }}/instances/?filter_fields=instance_status&filter_ops=IN&filter_values=online&paginated=false' \
-            -H 'Authorization: Bearer ${{ secrets.XC_BEARER_TOKEN }}' -o instance_list.json
+            -H 'Authorization: APIToken ${{ secrets.XC_API_TOKEN }}' -o instance_list.json
           cat instance_list.json
 
       - name: API call to NGINX One Saas Console - Push Config
         run: |
           RESPONSE=$(curl -X PUT --location 'https://nginx-tenant1.staging.volterra.us/api/nginx/one/namespaces/default/instances/${{ vars.N1SC_INSTANCE }}/config' \
-            -H 'Authorization: Bearer ${{ secrets.XC_BEARER_TOKEN }}' \
+            -H 'Authorization: APIToken ${{ secrets.XC_API_TOKEN }}' \
             --data '{ "aux": [], "conf_path": "/etc/nginx/nginx.conf", "configs": [ { "files": [ { "contents": "${{ env.NGINX_CONF_CONFIG_FILE }}", "mtime": "1970-01-01T00:00:00Z", "name": "nginx.conf", "size": 2756 }, { "contents": "${{ env.MIME_TYPES_CONFIG_FILE }}", "mtime": "1970-01-01T00:00:00Z", "name": "mime.types", "size": 2756} ], "name": "/etc/nginx" }, { "files": [ { "contents": "${{ env.DEFAULT_CONF_CONFIG_FILE }}", "mtime": "1970-01-01T00:00:00Z", "name": "default.conf", "size": 908 } ], "name": "/etc/nginx/conf.d" }], "object_id": "inst_OaV4v1QXRGm_T1atbMbLJw" }' \
             -H "Content-Type: application/json")
           echo "Response: $RESPONSE"
-          echo $RESPONSE | jq .
+          echo "$RESPONSE" | jq . || echo "Failed to parse JSON response"
+
 
