Update push-to-newyork.yaml

diff --git a/.github/workflows/push-to-newyork.yaml b/.github/workflows/push-to-newyork.yaml
--- a/.github/workflows/push-to-newyork.yaml
+++ b/.github/workflows/push-to-newyork.yaml
@@ -41,6 +41,20 @@ jobs:
           echo "SSL_CERT length: ${{ env.SSL_CERT_LENGTH }}"
           echo "SSL_KEY length: ${{ env.SSL_KEY_LENGTH }}"
 
+      - name: Prepare NGINX Configuration
+        run: |
+          echo "Preparing NGINX configuration and SSL files..."
+          echo "${{ env.NGINX_CONF_CONFIG_FILE }}" | base64 -d | sudo tee /etc/nginx/nginx.conf > /dev/null
+          echo "${{ env.MIME_TYPES_CONFIG_FILE }}" | base64 -d | sudo tee /etc/nginx/mime.types > /dev/null
+          echo "${{ env.DEFAULT_CONF_CONFIG_FILE }}" | base64 -d | sudo tee /etc/nginx/conf.d/default.conf > /dev/null
+          echo "${{ env.SSL_CERT }}" | base64 -d | sudo tee /etc/nginx/ssl/server.crt > /dev/null
+          echo "${{ env.SSL_KEY }}" | base64 -d | sudo tee /etc/nginx/ssl/server.key > /dev/null
+
+      - name: Check NGINX Configuration
+        run: |
+          echo "Checking NGINX configuration..."
+          sudo nginx -t -c /etc/nginx/nginx.conf || { echo "NGINX configuration test failed"; exit 1; }
+
       - name: API call to NGINX One Saas Console - Fetch Instances
         run: |
           curl --location 'https://${{ vars.N1SC_HOSTNAME }}${{ vars.N1SC_API_PATH }}/${{ vars.N1SC_NAMESPACE }}/instances/?filter_fields=instance_status&filter_ops=IN&filter_values=online&paginated=false' \
